language: r

cache: packages

warnings_are_errors: true

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'


notifications:
  email:
    recipients:
      - bossek@wi.uni-muenster.de
    on_success: change
    on_failure: always
