# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getAnglesToNearestNeighborsCPP <- function(coords, dist_mat) {
    .Call('_salesperson_getAnglesToNearestNeighborsCPP', PACKAGE = 'salesperson', coords, dist_mat)
}

getCentroidCoordinatesCPP <- function(coords) {
    .Call('_salesperson_getCentroidCoordinatesCPP', PACKAGE = 'salesperson', coords)
}

getDistancesToCentroidCPP <- function(coords, centroid_coords) {
    .Call('_salesperson_getDistancesToCentroidCPP', PACKAGE = 'salesperson', coords, centroid_coords)
}

getDistanceFeatureSetCPP <- function(d, dd) {
    .Call('_salesperson_getDistanceFeatureSetCPP', PACKAGE = 'salesperson', d, dd)
}

getFractionOfPointsNearBoundingBoxCPP <- function(coords, distanceFraction, normalize) {
    .Call('_salesperson_getFractionOfPointsNearBoundingBoxCPP', PACKAGE = 'salesperson', coords, distanceFraction, normalize)
}

getNearestNeighbourDistancesCPP <- function(dist_mat) {
    .Call('_salesperson_getNearestNeighbourDistancesCPP', PACKAGE = 'salesperson', dist_mat)
}

